---
sidebar: sidebar 
permalink: br-start-setup.html 
keywords: bluexp, backup, back up, restore, recovery, aws, azure 
summary: Antes de usar o BlueXP backup and recovery, siga algumas etapas para configurar os destinos de backup. 
---
= Configure destinos de backup antes de usar o BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Antes de usar o BlueXP backup and recovery, siga algumas etapas para configurar os destinos de backup.

Antes de começar, revise link:concept-start-prereq.html["pré-requisitos"] para garantir que seu ambiente esteja pronto.



== Prepare o destino da cópia de segurança

Prepare um ou mais dos seguintes destinos de backup:

* NetApp StorageGRID.
+
Consulte a https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Descubra o StorageGRID"^].

+
Consulte https://docs.netapp.com/us-en/storagegrid/index.html["Documentação do StorageGRID"^] para obter detalhes sobre StorageGRID.

* Serviços Web da Amazon. Consulte a https://docs.netapp.com/us-en/bluexp-s3-storage/index.html["Documentação do Amazon S3"^].
+
Faça o seguinte para preparar a AWS como destino de backup:

+
** Configure uma conta na AWS.
** Configure as permissões do S3 na AWS, listadas na próxima seção.
** Para obter detalhes sobre como gerenciar seu storage da AWS no BlueXP , https://docs.netapp.com/us-en/bluexp-setup-admin/task-viewing-amazon-s3.html["Gerencie seus buckets do Amazon S3"^] consulte .




* Microsoft Azure.
+
** Consulte a https://docs.netapp.com/us-en/bluexp-azure-netapp-files/index.html["Documentação do Azure NetApp Files"^].
** Configure uma conta no Azure.
** Configurar https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions.html["Permissões do Azure"^] no Azure.
** Para obter detalhes sobre como gerenciar seu storage Azure no BlueXP , https://docs.netapp.com/us-en/bluexp-blob-storage/task-view-azure-blob-storage.html["Gerencie suas contas de storage do Azure"^] consulte .




Após configurar as opções no próprio destino de backup, você o configurará posteriormente como um destino de backup no serviço de BlueXP backup and recovery . Para obter detalhes sobre como configurar o destino de backup no BlueXP backup and recovery, consulte link:br-start-discover-backup-targets.html["Descubra alvos de backup"] .



== Configure S3 permissões

Você precisará configurar dois conjuntos de permissões do AWS S3:

* Permissões para que o conetor crie e gerencie o bucket do S3.
* Permissões para o cluster do ONTAP no local para que ele possa ler e gravar dados no bucket do S3.


.Passos
. Certifique-se de que o conetor tem as permissões necessárias. Para obter detalhes, https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-aws.html["Permissões de política do BlueXP "] consulte .
+

NOTE: Ao criar backups nas regiões da AWS China, você precisa alterar o Nome de recurso da AWS "ARN" em todas as seções _Resource_ nas políticas do IAM de "aws" para "aws-cn"; por exemplo `arn:aws-cn:s3:::netapp-backup-*`.

. Quando você ativa o serviço, o assistente Backup solicitará que você insira uma chave de acesso e uma chave secreta. Essas credenciais são passadas para o cluster do ONTAP para que o ONTAP possa fazer backup e restaurar os dados para o bucket do S3. Para isso, você precisará criar um usuário do IAM com as seguintes permissões.
+
Consulte a https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["Documentação da AWS: Criando uma função para delegar permissões a um usuário do IAM"^] .

+
[%collapsible]
====
[source, json]
----
{
    "Version": "2012-10-17",
     "Statement": [
        {
           "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListBucket",
                "s3:ListAllMyBuckets",
                "s3:GetBucketLocation",
                "s3:PutEncryptionConfiguration"
            ],
            "Resource": "arn:aws:s3:::netapp-backup-*",
            "Effect": "Allow",
            "Sid": "backupPolicy"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject",
                "s3:ListAllMyBuckets",
                "s3:PutObjectTagging",
                "s3:GetObjectTagging",
                "s3:RestoreObject",
                "s3:GetBucketObjectLockConfiguration",
                "s3:GetObjectRetention",
                "s3:PutBucketObjectLockConfiguration",
                "s3:PutObjectRetention"
            ],
            "Resource": "arn:aws:s3:::netapp-backup*/*",
            "Effect": "Allow"
        }
    ]
}
----
====

