---
sidebar: sidebar 
permalink: br-start-faq.html 
keywords: backup and recovery faq, bluexp backup and recovery frequently asked questions 
summary: Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta. 
---
= Perguntas frequentes sobre BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Este FAQ pode ajudar se você está apenas procurando uma resposta rápida para uma pergunta.



== Implantação

*Você precisa de uma licença para usar o BlueXP backup and recovery versão Preview?*

Você pode usar os seguintes tipos de licença:

* Inscreva-se para uma avaliação gratuita de 30 dias.


*Como habilitar o BlueXP backup and recovery?* O BlueXP backup and recovery não exigem nenhuma ativação. A opção de backup e recuperação é habilitada automaticamente na navegação à esquerda do BlueXP .

Para começar, você precisa se inscrever ou entrar em Contato com seu representante de vendas da NetApp para experimentar este serviço. Em seguida, quando você usar o BlueXP  Connector, ele incluirá os recursos apropriados para o serviço.

Para começar a usar o BlueXP backup and recovery, clique em "Começar a descobrir cargas de trabalho" na página inicial.

* O BlueXP backup and recovery estão disponíveis nos modos padrão, restrito e privado?* No momento, a versão de visualização do BlueXP backup and recovery está disponível apenas no modo padrão. Fique atento para mais.

Para obter uma explicação sobre esses modos em todos os serviços BlueXP , https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Modos de implantação do BlueXP"^] consulte .



== Acesso

*Qual é o URL de BlueXP backup and recovery ?* Para o URL, em um navegador, digite: https://console.bluexp.netapp.com/["https://console.bluexp.netapp.com/backup-and-recovery"^] Para acessar o console do BlueXP .

*Como as permissões de acesso são tratadas?* Somente os administradores da organização podem iniciar o serviço e descobrir cargas de trabalho (porque isso envolve o compromisso com o uso de um recurso). Interações subsequentes podem ser feitas por qualquer função.

*Qual é a melhor resolução do dispositivo?* A resolução de dispositivo recomendada para BlueXP backup and recovery é 1920x1080 ou melhor.

*Qual navegador devo usar?* Qualquer navegador moderno funcionará.



== Interação com outros serviços

* O BlueXP backup and recovery reconhecem as configurações de proteção feitas no NetApp ONTAP?* Sim, o BlueXP backup and recovery descobrem agendamentos de snapshots definidos no ONTAP.

*Se você definir uma política usando o BlueXP backup and recovery, precisará fazer alterações futuras somente neste serviço?* Recomendamos que você faça alterações de política no serviço de BlueXP backup and recovery .



== Workloads

*O que compõe uma carga de trabalho?* Uma carga de trabalho é uma aplicação para a versão Preview 2025. Um workload inclui todos os volumes usados por uma única instância de aplicação. Por exemplo, uma instância de banco de dados do Microsoft SQL Server implantada em mssql3.host.com pode ter vol1 e vol2 para seus dados e logs, respectivamente. Esses volumes juntos constituem a carga de trabalho para aquela instância específica da instância de banco de dados.

*Quais cargas de trabalho o BlueXP backup and recovery suportam?*

Para a versão Preview 2025, o BlueXP backup and recovery podem identificar as seguintes cargas de trabalho: aplicativos do Microsoft SQL Server.

*O que é uma carga de trabalho "protegida"?* No BlueXP backup and recovery, uma carga de trabalho mostra um status “protegido” quando tem uma política de detecção primária habilitada.

*O que é uma carga de trabalho "em risco"?* Se uma carga de trabalho não tiver uma política de detecção primária habilitada, ela estará "em risco" mesmo que tenha uma política de backup e snapshot habilitada.

*Nova carga de trabalho adicionada, mas ainda não aparece* Se você adicionou uma nova carga de trabalho ao seu ambiente, inicie a descoberta novamente e aplique políticas de proteção para proteger esse novo recurso.



== Políticas de proteção

* O BlueXP backup and recovery estão cientes das configurações de proteção feitas no NetApp ONTAP?*

Sim, o BlueXP backup and recovery descobrem agendamentos de snapshots definidos no ONTAP e se ARP e FPolicy estão habilitados em uma carga de trabalho descoberta. As informações que você vê inicialmente no Painel são agregadas de outras soluções e produtos da NetApp.

* O BlueXP backup and recovery estão cientes das políticas já criadas no SnapCenter?*

Sim, se você tiver cargas de trabalho gerenciadas no SnapCenter, as políticas gerenciadas por esses produtos serão trazidas para o BlueXP backup and recovery.

*Você pode modificar as políticas transferidas do SnapCenter?*

Sim, você pode modificar políticas que foram gerenciadas pelo SnapCenter no BlueXP backup and recovery.

*Se existirem políticas do ONTAP (já habilitadas no Gerenciador do Sistema, como ARP, FPolicy e snapshots), elas serão alteradas no BlueXP backup and recovery?*

Não. O BlueXP backup and recovery não modificam nenhuma política de detecção existente (configurações ARP, FPolicy) do ONTAP.

*O que acontece se você adicionar novas políticas no SnapCenter após se inscrever no BlueXP backup and recovery?*

O BlueXP backup and recovery reconhecem quaisquer novas políticas criadas no SnapCenter.

*Você pode alterar as políticas do ONTAP?*

Sim, você pode alterar as políticas do ONTAP no BlueXP backup and recovery. Você também pode criar novas políticas no BlueXP backup and recovery e aplicá-las às cargas de trabalho. Esta ação substitui as políticas ONTAP existentes pelas políticas criadas no BlueXP backup and recovery.
