---
sidebar: sidebar 
permalink: br-use-restore-kubernetes-applications.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: O BlueXP backup and recovery permitem restaurar aplicativos que você protegeu com uma política de proteção. 
---
= Restaurar aplicativos Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O BlueXP backup and recovery permitem restaurar aplicativos protegidos com uma política de proteção. Para restaurar um aplicativo, ele precisa ter o status de proteção "Protegido" e uma política de proteção associada. Você restaura um aplicativo usando um ponto de restauração, que consiste no snapshot local, no snapshot secundário e no backup no repositório de objetos. Você pode restaurar um aplicativo usando o arquivo local, secundário ou do repositório de objetos.

.Função BlueXP necessária
Administrador da organização ou administrador do SnapCenter . link:reference-roles.html["Saiba mais sobre as funções de acesso de BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do BlueXP para todos os serviços"^] .

.Passos
. No BlueXP backup and recovery, selecione *Inventário*.
. Escolha uma carga de trabalho do Kubernetes e selecione *Exibir* na coluna Hosts da carga de trabalho.
. Na lista de aplicativos, escolha um aplicativo que você deseja restaurar e selecione o menu Ações associado.
. Selecione *Exibir e restaurar*.
+
A lista de pontos de restauração é exibida.

. Abra o menu Ações do ponto de restauração que você deseja usar e selecione *Restaurar*.


[discrete]
===== Configurações gerais

. Escolha a origem da restauração (local, secundária ou armazenamento de objetos).
. Escolha o cluster de destino na lista *Cluster*.
. Escolha o namespace de destino da restauração (original ou novo).
+
Observe que a restauração para um cluster diferente e o namespace original não são suportados.

. Selecione *seguinte*.


[discrete]
===== Seleção de recursos

. Escolha se deseja restaurar todos os recursos associados ao aplicativo ou usar um filtro para selecionar recursos específicos para restaurar:


[role="tabbed-block"]
====
.Restaurar todos os recursos
--
. Selecione *Restaurar todos os recursos*.
. Selecione *seguinte*.


--
.Restaurar recursos específicos
--
. Selecione *Recursos seletivos*.
. Escolha o comportamento do filtro de recursos. Se você escolher *Incluir*, os recursos selecionados serão restaurados. Se você escolher *Excluir*, os recursos selecionados não serão restaurados.
. Selecione *Adicionar regras* para adicionar regras que definem filtros para a seleção de recursos. Você precisa de pelo menos uma regra para filtrar recursos.
+
Cada regra pode filtrar critérios como namespace do recurso, rótulos, grupo, versão e tipo.

. Selecione *Salvar* para salvar cada regra.
. Depois de adicionar todas as regras necessárias, selecione *Pesquisar* para ver os recursos disponíveis no arquivo de backup que correspondem aos seus critérios de filtro.
. Quando estiver satisfeito com os resultados, selecione *Avançar*.


--
====
[discrete]
===== Configurações de destino

. Escolha restaurar para a classe de armazenamento padrão ou para uma classe de armazenamento diferente.
. Opcionalmente, se você optar por restaurar para uma classe de armazenamento diferente, selecione uma classe de armazenamento de destino correspondente a cada classe de armazenamento de origem. A classe de armazenamento de destino deve estar disponível no cluster de destino.
. Selecione *Restaurar*.

