---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho VMware com BlueXP backup and recovery do NetApp BlueXP. 
---
= Proteja as cargas de trabalho do VMware com a visão geral de BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja suas VMs e armazenamentos de dados VMware com BlueXP backup and recovery.  O BlueXP backup and recovery oferecem operações de backup e restauração rápidas, com eficiência de espaço, consistentes em caso de falhas e consistentes com a VM.  Você pode fazer backup de cargas de trabalho do VMware no Amazon Web Services S3 ou StorageGRID e restaurar cargas de trabalho do VMware em um host VMware local.


NOTE: Esta versão do BlueXP backup and recovery oferece suporte apenas ao VMware vCenter e não descobre vVols ou VMs em vVols.

Use o BlueXP backup and recovery para implementar uma estratégia 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem.  Os benefícios da abordagem 3-2-1 incluem:

* Várias cópias de dados fornecem proteção em várias camadas contra ameaças internas (internas) e externas à segurança cibernética.
* Vários tipos de Mídia garantem a viabilidade do failover em caso de falha física ou lógica de um tipo de Mídia.
* A cópia no local facilita restaurações rápidas, com cópias externas disponíveis caso a cópia no local seja comprometida.


[]
====
*NOTA* Para alternar entre as versões de interface de usuário de BlueXP backup and recovery , consulte link:br-start-switch-ui.html["Mudar para a interface de usuário de BlueXP backup and recovery"] .

====
Você pode usar o BlueXP backup and recovery para executar as seguintes tarefas relacionadas às cargas de trabalho do VMware:

* link:br-use-vmware-discovery.html["Descubra as cargas de trabalho da VMware"]
* link:br-use-vmware-protection-groups.html["Crie e gerencie grupos de proteção para cargas de trabalho do VMware"]
* link:br-use-vmware-backup.html["Fazer backup de cargas de trabalho do VMware"]
* link:br-use-vmware-restore.html["Restaurar cargas de trabalho do VMware"]

