---
sidebar: sidebar 
permalink: br-use-mssql-protect-overview.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery 
summary: Você pode fazer backup de dados de aplicativos do Microsoft SQL Server de sistemas ONTAP locais para Amazon Web Services, Microsoft Azure e StorageGRID, garantindo a proteção dos seus dados. Os backups são gerados e armazenados automaticamente em um armazenamento de objetos em sua conta de nuvem pública ou privada. Você pode implementar uma estratégia 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem. 
---
= Visão geral da proteção de cargas de trabalho do Microsoft SQL com BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja os dados dos seus aplicativos Microsoft SQL Server de sistemas ONTAP locais para Amazon Web Services, Microsoft Azure ou StorageGRID usando o BlueXP backup and recovery. Os backups são gerados e armazenados automaticamente em um repositório de objetos na sua conta de nuvem pública ou privada, com base nas políticas que você criar. Você pode implementar uma estratégia 3-2-1, na qual você tem 3 cópias dos seus dados de origem em 2 sistemas de armazenamento diferentes, além de 1 cópia na nuvem.

Os benefícios da abordagem 3-2-1 incluem:

* Várias cópias de dados fornecem proteção em várias camadas contra ameaças internas (internas) e externas à segurança cibernética.
* Vários tipos de Mídia garantem a viabilidade do failover em caso de falha física ou lógica de um tipo de Mídia.
* A cópia no local facilita restaurações rápidas, com cópias externas disponíveis caso a cópia no local seja comprometida.


O BlueXP backup and recovery aproveitam a tecnologia de replicação de dados NetApp SnapMirror para garantir que todos os backups estejam totalmente sincronizados, criando cópias instantâneas e transferindo-as para os locais de backup.

Você pode atingir as seguintes metas de proteção:

* link:concept-start-prereq-snapcenter-import.html["Configurar itens adicionais se importar do SnapCenter"]
* link:br-start-discover.html["Descubra cargas de trabalho do Microsoft SQL Server e, opcionalmente, importe recursos do SnapCenter"]
* link:br-use-mssql-backup.html["Faça backup de cargas de trabalho com snapshots locais no armazenamento primário ONTAP local"]
* link:br-use-mssql-backup.html["Replique cargas de trabalho para armazenamento secundário ONTAP"]
* link:br-use-mssql-backup.html["Fazer backup de cargas de trabalho em um local de armazenamento de objetos"]
* link:br-use-mssql-backup.html["Faça backup das cargas de trabalho agora"]
* link:br-use-mssql-restore-overview.html["Restaurar cargas de trabalho"]
* link:br-use-mssql-clone.html["Clonar cargas de trabalho"]
* link:br-use-manage-inventory.html["Gerenciar inventário de cargas de trabalho"]
* link:br-use-manage-snapshots.html["Gerenciar snapshots"]


Para fazer backup de cargas de trabalho, normalmente você cria políticas que controlam as operações de backup e restauração. Consulte link:br-use-policies-create.html["Criar políticas"] para obter mais informações.

.Destinos de cópia de segurança suportados
O BlueXP backup and recovery permitem que você faça backup de instâncias e bancos de dados do Microsoft SQL Server dos seguintes ambientes de trabalho de origem para os seguintes ambientes de trabalho secundários e armazenamento de objetos em provedores de nuvem pública e privada. As cópias Snapshot residem no ambiente de trabalho de origem.

[cols="33,33,33"]
|===
| Fonte ambiente de trabalho | Ambiente de trabalho secundário (replicação) | Armazenamento de Objetos de Destino (Backup) 


| Cloud Volumes ONTAP na AWS | Cloud Volumes ONTAP no sistema ONTAP on-premises da AWS | Amazon S3 ONTAP S3 


| Cloud Volumes ONTAP no Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure | Azure Blob ONTAP S3 


| Sistema ONTAP no local | Sistema ONTAP no local da Cloud Volumes ONTAP | Amazon S3 Azure Blob NetApp StorageGRID ONTAP S3 


| Amazon FSX para NetApp ONTAP | Amazon FSX para NetApp ONTAP | NA ifdef::gcp[] fim se::gcp[] ifdef::gcp[] fim se::gcp[] 
|===
.Destinos de restauração suportados
Você pode restaurar instâncias e bancos de dados do Microsoft SQL Server de um backup que reside no armazenamento primário ou em um ambiente de trabalho secundário (um volume replicado) ou em um armazenamento de objetos (um arquivo de backup) para os seguintes ambientes de trabalho. As cópias Snapshot residem no ambiente de trabalho de origem e podem ser restauradas somente nesse mesmo sistema.

[cols="33,33,33"]
|===
2+| Do local do arquivo de backup | Para o ambiente de trabalho de destino 


| *Object Store (Backup)* | *Sistema secundário (replicação)* |  


| Amazon S3 | Cloud Volumes ONTAP no sistema ONTAP on-premises da AWS | Volumes de nuvem no sistema ONTAP local da AWS ONTAP S3 


| Blob do Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure | Cloud Volumes ONTAP no sistema ONTAP local do Azure ONTAP S3 ifdef::gcp[] endif::gcp[] 


| StorageGRID | Sistema ONTAP no local da Cloud Volumes ONTAP | Sistema ONTAP local ONTAP S3 


| Amazon FSX para NetApp ONTAP | Amazon FSX para NetApp ONTAP | N / D 
|===

NOTE: Referências a "sistemas ONTAP locais" incluem sistemas FAS e AFF .
