---
sidebar: sidebar 
permalink: br-use-manage-execution-hook-templates.html 
keywords: hooks, execution hooks, exec hooks, hook, execution, script, postscript, prescript, post, pre, run, backup, snapshot, freeze 
summary: O BlueXP backup and recovery permitem que você gerencie ganchos de execução para agir antes ou depois das operações de proteção do aplicativo. 
---
= Gerenciar modelos de ganchos de execução de BlueXP backup and recovery para cargas de trabalho do Kubernetes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um gancho de execução é uma ação personalizada que você pode configurar para ser executada em conjunto com uma operação de proteção de dados de um aplicativo Kubernetes gerenciado. Por exemplo, se você tiver um aplicativo de banco de dados, poderá usar um gancho de execução para pausar todas as transações de banco de dados antes de um snapshot e retomar as transações após a conclusão do snapshot. Isso garante snapshots consistentes com aplicativos. Ao criar um modelo de gancho de execução, você pode especificar o tipo de gancho, o script a ser executado e quaisquer filtros que determinem a quais contêineres o gancho se aplica. Você pode então usar o modelo para associar ganchos de execução aos seus aplicativos.

.Função BlueXP necessária
Administrador da organização ou administrador do SnapCenter . link:reference-roles.html["Saiba mais sobre as funções de acesso de BlueXP backup and recovery"] .  https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Saiba mais sobre as funções de acesso do BlueXP para todos os serviços"^] .



== Tipos de ganchos de execução

O BlueXP backup and recovery oferecem suporte aos seguintes tipos de ganchos de execução, com base em quando eles podem ser executados:

* Pré-instantâneo
* Pós-snapshot
* Pré-backup
* Pós-backup
* Pós-restauração




=== Ordem de execução

Quando uma operação de proteção de dados é executada, os eventos de gancho de execução ocorrem na seguinte ordem:

. Todos os ganchos de execução personalizados de pré-operação aplicáveis são executados nos contentores apropriados. Você pode criar e executar quantos ganchos de pré-operação personalizados você precisar, mas a ordem de execução desses ganchos antes da operação não é garantida nem configurável.
. Ocorrem travamentos do sistema de arquivos, se aplicável.
. A operação de proteção de dados é realizada.
. Os sistemas de arquivos congelados não estão congelados, se aplicável.
. Todos os ganchos de execução pós-operação personalizados aplicáveis são executados nos contentores apropriados. Você pode criar e executar quantos ganchos de pós-operação personalizados você precisar, mas a ordem de execução desses ganchos após a operação não é garantida nem configurável.


Se você criar vários ganchos de execução do mesmo tipo (por exemplo, pré-snapshot), a ordem de execução desses ganchos não será garantida. No entanto, a ordem de execução de ganchos de diferentes tipos é garantida. Por exemplo, a seguinte é a ordem de execução de uma configuração que tem todos os diferentes tipos de ganchos:

. Ganchos pré-instantâneos executados
. Ganchos pós-snapshot executados
. Ganchos pré-backup executados
. Ganchos pós-backup executados



NOTE: O exemplo de pedido anterior só se aplica quando você executa um backup que não usa um snapshot existente.


NOTE: Você deve sempre testar seus scripts de gancho de execução antes de habilitá-los em um ambiente de produção. Você pode usar o comando 'kubectl exec' para testar convenientemente os scripts. Depois de habilitar os ganchos de execução em um ambiente de produção, teste os snapshots e backups resultantes para garantir que eles sejam consistentes. Você pode fazer isso clonando o aplicativo para um namespace temporário, restaurando o snapshot ou o backup e testando o aplicativo.


NOTE: Se um gancho de execução pré-snapshot adicionar, alterar ou remover recursos do Kubernetes, essas alterações serão incluídas no snapshot ou backup e em qualquer operação de restauração subsequente.



== Notas importantes sobre ganchos de execução personalizados

Considere o seguinte ao Planejar ganchos de execução para seus aplicativos.

* Um gancho de execução deve usar um script para executar ações. Muitos ganchos de execução podem referenciar o mesmo script.
* Os ganchos de execução precisam ser escritos no formato de scripts de shell executáveis.
* O tamanho do script está limitado a 96kbMB.
* As configurações de gancho de execução e quaisquer critérios correspondentes são usados para determinar quais ganchos são aplicáveis a uma operação de instantâneo, backup ou restauração.



NOTE: Como os ganchos de execução geralmente reduzem ou desativam completamente a funcionalidade do aplicativo em que estão sendo executados, você deve sempre tentar minimizar o tempo que seus ganchos de execução personalizados demoram para serem executados. Se você iniciar uma operação de backup ou snapshot com ganchos de execução associados, mas depois cancelá-la, os ganchos ainda poderão ser executados se a operação de backup ou snapshot já tiver começado. Isso significa que a lógica usada em um gancho de execução pós-backup não pode assumir que o backup foi concluído.



== Filtros de gancho de execução

Quando você adiciona ou edita um gancho de execução para um aplicativo, você pode adicionar filtros ao gancho de execução para gerenciar quais contentores o gancho corresponderá. Os filtros são úteis para aplicativos que usam a mesma imagem de contentor em todos os contentores, mas podem usar cada imagem para um propósito diferente (como o Elasticsearch). Os filtros permitem criar cenários onde os ganchos de execução são executados em alguns, mas não necessariamente em todos os contentores idênticos. Se você criar vários filtros para um único gancho de execução, eles serão combinados com um operador LÓGICO E. Você pode ter até 10 filtros ativos por gancho de execução.

Cada filtro que você adicionar a um gancho de execução usa uma expressão regular para corresponder a containers em seu cluster. Quando um gancho corresponde a um recipiente, o gancho executará o script associado nesse recipiente. As expressões regulares para filtros usam a sintaxe da expressão regular 2 (RE2), que não suporta a criação de um filtro que exclui contentores da lista de correspondências. Para obter informações sobre a sintaxe que o BlueXP backup and recovery oferecem suporte para expressões regulares em filtros de gancho de execução, consulte  https://github.com/google/re2/wiki/Syntax["Suporte à sintaxe da expressão regular 2 (RE2)"^] .


NOTE: Se você adicionar um filtro de namespace a um gancho de execução que é executado após uma operação de restauração ou clone e a origem e destino de restauração ou clone estiverem em namespaces diferentes, o filtro de namespace será aplicado somente ao namespace de destino.



== Exemplos de gancho de execução

Visite o https://github.com/NetApp/Verda["Projeto NetApp Verda GitHub"] para baixar ganchos de execução reais para aplicativos populares, como Apache Cassandra e Elasticsearch. Você também pode ver exemplos e obter ideias para estruturar seus próprios ganchos de execução personalizados.



== Crie um modelo de gancho de execução

Você pode criar um modelo de gancho de execução personalizado que pode ser usado para executar ações antes ou depois de uma operação de proteção de dados em um aplicativo.

.Passos
. No BlueXP, vá em *Proteção* > *Backup e recuperação*.
. Selecione a guia *Configurações*.
. Expanda a seção *Modelo de gancho de execução*.
. Selecione *Criar modelo de gancho de execução*.
. Digite um nome para o gancho de execução.
. Escolha um tipo de gancho. Por exemplo, um gancho pós-restauração será executado após a conclusão da operação de restauração.
. Na caixa de texto *Script*, insira o script de shell executável que você deseja executar como parte do modelo de gancho de execução. Opcionalmente, você pode selecionar *Carregar script* para carregar um arquivo de script.
. Selecione *criar*.
+
O modelo é criado e aparece na lista de modelos na seção *Modelo de gancho de execução*.


