---
sidebar: sidebar 
permalink: br-use-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho VMware com BlueXP backup and recovery do NetApp BlueXP. 
---
= Proteja as cargas de trabalho do VMware com a visão geral de BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja suas cargas de trabalho VMware com o BlueXP backup and recovery. O BlueXP backup and recovery oferecem operações de backup e restauração rápidas, com economia de espaço, consistentes em caso de falhas e consistentes com a VM para VMs, datastores e VMDKs.

É possível fazer backup de armazenamentos de dados no Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform e StorageGRID e restaurar máquinas virtuais de volta ao plug-in do SnapCenter no local para host VMware vSphere.

[]
====
*NOTA* Este recurso usa uma versão anterior da interface de usuário de BlueXP backup and recovery . Para alternar entre as versões de interface de usuário de BlueXP backup and recovery , consulte link:br-start-switch-ui.html["Mudar para a interface de usuário de BlueXP backup and recovery"] .

====
Para obter instruções sobre como usar a interface de usuário de BlueXP backup and recovery , consulte os seguintes tópicos:
