---
sidebar: sidebar 
permalink: concept-start-prereq.html 
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, backup and recovery 
summary: Comece a usar o BlueXP backup and recovery verificando a prontidão do seu ambiente operacional, do BlueXP Connector e da conta BlueXP . Para usar o BlueXP backup and recovery, você precisará destes pré-requisitos. 
---
= Pré-requisitos de BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comece a usar o BlueXP backup and recovery verificando a prontidão do seu ambiente operacional, do BlueXP Connector e da conta BlueXP . Para usar o BlueXP backup and recovery, você precisará destes pré-requisitos.



== Para o ONTAP 9.8 e posterior

Uma licença ONTAP One deve ser habilitada na instância ONTAP local.



== Para backups em armazenamento de objetos

Para usar o armazenamento de objetos como destinos de backup, você precisa de uma conta no AWS S3, Microsoft Azure Blob, StorageGRID ou ONTAP e as permissões de acesso apropriadas configuradas.

* link:prev-ontap-protect-overview.html["Proteger os dados de volume do ONTAP"]
* link:br-use-mssql-protect-overview.html["Proteja seus bancos de dados do Microsoft SQL Server"]
* link:prev-vmware-protect-overview.html["Proteja as cargas de trabalho das suas máquinas virtuais"]




== Em BlueXP

* Um usuário do BlueXP deve ter a função e os privilégios necessários para executar operações em cargas de trabalho do Microsoft SQL Server e do Kubernetes. Para descobrir os recursos, você deve ter a função de Superadministrador de BlueXP backup and recovery . Consulte link:reference-roles.html["Acesso baseado em função de BlueXP backup and recovery aos recursos"] para obter detalhes sobre as funções e permissões necessárias para executar operações no BlueXP backup and recovery.
* Uma organização BlueXP com pelo menos um Conector BlueXP ativo que se conecta a clusters ONTAP locais ou Cloud Volumes ONTAP. Consulte o *Processo de configuração da Visualização Inicial* abaixo.
* Pelo menos um ambiente de trabalho BlueXP com um cluster NetApp ONTAP local ou Cloud Volumes ONTAP .
* Um conector BlueXP
+
 https://docs.netapp.com/us-en/bluexp-setup-admin/concept-connectors.html["Saiba como configurar um conetor BlueXP"]Consulte e https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos padrão do BlueXP"^].

+
** A versão de visualização requer o sistema operacional Ubuntu 22.04 LTS para o Connector.






=== Configure o BlueXP

O próximo passo é configurar o BlueXP e o serviço de BlueXP backup and recovery .

Revisão https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-checklist-cm.html["Requisitos padrão do BlueXP"^].



=== Crie um conetor BlueXP

Você deve entrar em contato com sua equipe de produtos da NetApp para experimentar este serviço. Em seguida, quando você usar o BlueXP  Connector, ele incluirá os recursos apropriados para o serviço.

Para criar um conetor no BlueXP  antes de usar o serviço, consulte a documentação do BlueXP  que descreve https://docs.netapp.com/us-en/cloud-manager-setup-admin/concept-connectors.html["Como criar um conetor BlueXP"^]o .

.Onde instalar o conector BlueXP
Para concluir uma operação de restauração, o Connector pode ser instalado nos seguintes locais:

ifdef::aws[]

* Para o Amazon S3, o Connector pode ser implantado em suas instalações.


endif::aws[]

ifdef::azure[]

* Para o Azure Blob, o Conector pode ser implantado em suas instalações.


endif::azure[]

ifdef::gcp[]

endif::gcp[]

* Para o StorageGRID, o Connector deve ser implantado em suas instalações; com ou sem acesso à Internet.
* Para o ONTAP S3, o conetor pode ser implantado em suas instalações (com ou sem acesso à Internet) ou em um ambiente de provedor de nuvem



NOTE: Referências a "sistemas ONTAP locais" incluem sistemas FAS e AFF .



== Requisitos de host do Microsoft SQL Server

Para usar o BlueXP backup and recovery para cargas de trabalho do SQL Server, você precisa dos seguintes pré-requisitos de sistema host, espaço e dimensionamento.

[cols="33,66a"]
|===
| Item | Requisitos 


| Sistemas operacionais  a| 
Microsoft Windows Para obter as informações mais recentes sobre as versões suportadas, consulte o  https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Ferramenta de Matriz de interoperabilidade do NetApp"^] .



| Versões do Microsoft SQL Server  a| 
A versão 2012 e posteriores são suportadas pelo VMware Virtual Machine File System (VMFS) e pelo VMware Virtual Machine Disk (VMDK) NFS.



| Versão do SnapCenter Server  a| 
O SnapCenter Server versão 5.0 ou superior é necessário se você for importar seus dados existentes do SnapCenter para o BlueXP backup and recovery.


NOTE: Se você já tem o SnapCenter, primeiro verifique se atendeu aos pré-requisitos antes de importar do SnapCenter. link:concept-start-prereq-snapcenter-import.html["Pré-requisitos para importar recursos do SnapCenter"]Consulte .



| RAM mínima para o plug-in no host do SQL Server  a| 
1 GB



| Espaço mínimo de instalação e log para o plug-in no host do SQL Server  a| 
5 GB

Aloque espaço em disco suficiente e monitore o consumo de armazenamento pela pasta de logs. O espaço de log necessário varia de acordo com o número de backups realizados e a frequência das operações de proteção de dados. Se não houver espaço suficiente, os logs não serão criados para as operações.



| Pacotes de software necessários  a| 
* Pacote de hospedagem do ASP.NET Core Runtime 8.0.12 (e todos os patches 8.0.x subsequentes)
* PowerShell Core 7.4.2


Para obter as informações mais recentes sobre versões suportadas, consulte o https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT#welcome["Ferramenta de Matriz de interoperabilidade do NetApp"^].

|===


== Para proteger aplicativos Kubernetes

Você precisa de requisitos específicos para descobrir recursos do Kubernetes e proteger seus aplicativos Kubernetes.

Para requisitos do BlueXP , consulte <<Em BlueXP>> .

* Um sistema ONTAP primário (ONTAP 9.16.1 ou posterior)
* Um cluster do Kubernetes - As distribuições e versões do Kubernetes suportadas incluem:
+
** Anthos On-Prem (VMware) e Anthos em bare metal 1.16
** Kubernetes 1.27 - 1.33
** OpenShift 4.10 - 4.18
** Rancher Kubernetes Engine 2 (RKE2) v1.26.7+rke2r1, v1.28.5+rke2r1


* NetApp Trident 24.10 ou posterior
* NetApp Trident Protect 25.07 ou posterior (instalado durante a descoberta da carga de trabalho do Kubernetes)
* NetApp Trident Protect Connector 25.07 ou posterior (instalado durante a descoberta da carga de trabalho do Kubernetes)
+
** Certifique-se de que a porta TCP 443 não esteja filtrada na direção de saída entre o cluster Kubernetes, o Trident Protect Connector e o proxy Trident Protect.



