---
sidebar: sidebar 
permalink: prev-reference-aws-archive-storage-tiers.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: O backup e a recuperação do BlueXP  são compatíveis com duas classes de armazenamento de arquivamento S3 e a maioria das regiões. 
---
= Camadas de armazenamento de arquivo AWS com suporte para BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
O backup e a recuperação do BlueXP  são compatíveis com duas classes de armazenamento de arquivamento S3 e a maioria das regiões.

[]
====
*NOTA* Para alternar entre as versões de interface de usuário de BlueXP backup and recovery , consulte link:br-start-switch-ui.html["Mudar para a interface de usuário de BlueXP backup and recovery"] .

====


== Classes de armazenamento de arquivamento S3 compatíveis para backup e recuperação do BlueXP 

Quando os arquivos de backup são criados inicialmente, eles são armazenados no armazenamento S3 _Standard_. Esse nível é otimizado para armazenar dados que são acessados com pouca frequência, mas que também permite acessá-los imediatamente. Depois de 30 dias, os backups passam para a classe de armazenamento S3 _Standard-unusual access_ para economizar nos custos.

Se os clusters de origem estiverem executando o ONTAP 9.10,1 ou superior, você poderá optar por categorizar backups no armazenamento _S3 Glacier_ ou _S3 Glacier Deep Archive_ após um determinado número de dias (normalmente mais de 30 dias) para otimização de custos adicional. Você pode definir isso para "0" ou para 1-999 dias. Se você configurá-lo para "0" dias, você não pode alterá-lo mais tarde para 1-999 dias.

Os dados nesses níveis não podem ser acessados imediatamente quando necessário e exigirão um custo de recuperação mais alto, portanto, você precisa considerar a frequência com que você pode precisar restaurar dados desses arquivos de backup arquivados. Consulte a seção nesta página sobre como restaurar dados do armazenamento de arquivos.

* Se você selecionar nenhum nível de arquivamento na primeira política de backup ao ativar o backup e a recuperação do BlueXP , o _S3 Glacier_ será a única opção de arquivamento para políticas futuras.
* Se você selecionar _S3 Glacier_ em sua primeira política de backup, poderá alterar para o nível _S3 Glacier Deep Archive_ para futuras políticas de backup para esse cluster.
* Se você selecionar _S3 Glacier Deep Archive_ em sua primeira política de backup, esse nível será o único nível de arquivamento disponível para políticas futuras de backup para esse cluster.


Observe que ao configurar o backup e a recuperação do BlueXP  com esse tipo de regra de ciclo de vida, você não deve configurar nenhuma regra de ciclo de vida ao configurar o bucket na sua conta da AWS.

https://aws.amazon.com/s3/storage-classes/["Saiba mais sobre as classes de armazenamento S3"^].



== Restaurar dados do armazenamento de arquivamento

Embora armazenar arquivos de backup mais antigos no armazenamento de arquivamento seja muito mais barato do que o armazenamento Standard ou Standard-IA, acessar dados de um arquivo de backup no armazenamento de arquivamento para operações de restauração levará um tempo maior e custará mais dinheiro.

Quanto custa restaurar dados do Amazon S3 Glacier e do Amazon S3 Glacier Deep Archive?:: Há 3 prioridades de restauração que você pode escolher ao recuperar dados do Amazon S3 Glacier e 2 prioridades de restauração ao recuperar dados do Amazon S3 Glacier Deep Archive. S3 Glacier Deep Archive custa menos de S3 Glacier:
+
--
[cols="25,25,25,25"]
|===
| Nível de arquivamento 3+| Restaurar prioridade e custo 


|  | *Alta* | *Standard* | *Baixo* 


| *S3 Glacier* | Recuperação mais rápida, custo mais alto | Recuperação mais lenta, menor custo | Recuperação mais lenta, menor custo 


| *S3 Glacier Deep Archive* |  | Recuperação mais rápida, custo mais elevado | Recuperação mais lenta, menor custo 
|===
Cada método tem uma taxa de recuperação por GB diferente e taxa por solicitação. Para obter a definição de preço detalhada do S3 Glacier por região da AWS, visite o https://aws.amazon.com/s3/pricing/["Página de definição de preço do Amazon S3"^].

--
Quanto tempo levará para restaurar meus objetos arquivados no Amazon S3 Glacier?:: Existem 2 partes que compõem o tempo total de restauração:
+
--
* *Tempo de recuperação*: O tempo para recuperar o arquivo de backup do arquivo e colocá-lo em armazenamento padrão. Isso às vezes é chamado de tempo de "reidratação". O tempo de recuperação é diferente dependendo da prioridade de restauração escolhida.
+
[cols="25,20,20,20"]
|===
| Nível de arquivamento 3+| Restaurar prioridade e tempo de recuperação 


|  | *Alta* | *Standard* | *Baixo* 


| *S3 Glacier* | 3-5 minutos | 3-5 horas | 5-12 horas 


| *S3 Glacier Deep Archive* |  | 12 horas | 48 horas 
|===
* *Tempo de restauração*: O tempo para restaurar os dados do arquivo de backup no armazenamento padrão. Esse tempo não é diferente da operação de restauração típica diretamente do armazenamento padrão, quando não está usando uma camada de arquivamento.


Para obter mais informações sobre as opções de recuperação do Amazon S3 Glacier e do S3 Glacier Deep Archive, https://aws.amazon.com/s3/faqs/#Amazon_S3_Glacier["As perguntas frequentes sobre essas classes de armazenamento da Amazon"^] consulte .

--

