---
sidebar: sidebar 
permalink: prev-vmware-protect-overview.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho VMware com BlueXP backup and recovery do NetApp BlueXP. 
---
= Proteja cargas de trabalho de máquinas virtuais no BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Proteja as cargas de trabalho das suas máquinas virtuais com o BlueXP backup and recovery. O BlueXP backup and recovery oferece operações de backup e restauração rápidas, com economia de espaço, consistentes em caso de falhas e consistentes com a VM para VMs, datastores e VMDKs.

É possível fazer backup de armazenamentos de dados no Amazon Web Services S3, Microsoft Azure Blob, Google Cloud Platform e StorageGRID e restaurar máquinas virtuais de volta ao plug-in do SnapCenter no local para host VMware vSphere.

[]
====
*NOTA* Para alternar entre cargas de trabalho de BlueXP backup and recovery , consulte link:br-start-switch-ui.html["Mude para diferentes cargas de trabalho de BlueXP backup and recovery"] .

====
Para obter instruções sobre como proteger cargas de trabalho de máquinas virtuais, consulte os seguintes tópicos:

* link:prev-vmware-policy-create.html["Crie uma política para cargas de trabalho do VMware"]
* link:prev-vmware-backup-aws.html["Fazer backup de datastores VMware no Amazon Web Services"]
* link:prev-vmware-backup-azure.html["Fazer backup de datastores VMware no Microsoft Azure"]
* link:prev-vmware-backup-gcp.html["Faça backup dos datastores VMware no Google Cloud Platform"]
* link:prev-vmware-backup-storagegrid.html["Fazer backup dos datastores VMware no StorageGRID"]
* link:prev-vmware-restore.html["Restaurar cargas de trabalho do VMware"]
* link:prev-vmware-manage.html["Gerenciar proteção para cargas de trabalho VMware"]

