---
sidebar: sidebar 
permalink: prev-vmware-register-snapcenter.html 
keywords: backing up, back up, backup, backup application data, Amazon Web services, AWS, BlueXP backup and recovery, Oracle database, Microsoft SQL Server database, SAP HANA database 
summary: Proteja suas cargas de trabalho VMware com BlueXP backup and recovery do NetApp BlueXP. 
---
= Registre o SnapCenter Plug-in for VMware vSphere para usar com BlueXP backup and recovery
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve registrar o plug-in SnapCenter para o host VMware vSphere no backup e recuperação do BlueXP para que os armazenamentos de dados e máquinas virtuais sejam exibidos. Somente um usuário com acesso administrativo pode Registrar o plug-in do SnapCenter para o host VMware vSphere.

[]
====
*NOTA* Para alternar entre cargas de trabalho de BlueXP backup and recovery , consulte link:br-start-switch-ui.html["Mude para diferentes cargas de trabalho de BlueXP backup and recovery"] .

====
.Passos
. Na interface do usuário do BlueXP , selecione *Proteção* > *Backup e recuperação* > *Máquinas virtuais*.
. No menu suspenso *Configurações*, selecione * SnapCenter Plug-in for VMware vSphere*.
. Selecione *Registrar SnapCenter Plug-in for VMware vSphere*.
. Especifique os seguintes detalhes:
+
.. No campo Plug-in do SnapCenter para VMware vSphere, especifique o FQDN ou o endereço IP do plug-in do SnapCenter para o host VMware vSphere.
.. No campo porta , especifique o número da porta na qual o plug-in do SnapCenter para o host VMware vSphere está sendo executado.
+
Você deve garantir que a comunicação esteja aberta entre o plug-in do SnapCenter no local para o host VMware vSphere que está sendo executado na porta 8144 padrão e na instância do BlueXP  Connector que pode ser executado em qualquer provedor de nuvem (Amazon Web Services, Microsoft Azure, Google Cloud Platform) ou no local.

.. No campo Nome de usuário e senha , especifique as credenciais do usuário do vCenter com a função de administrador.


. Selecione *Registe-se*.


*Depois de terminar*

Selecione *Backup e recuperação* > *Máquinas virtuais* para visualizar todos os armazenamentos de dados e máquinas virtuais que estão protegidos usando o SnapCenter Plug-in for VMware vSphere .
