---
settings:
  name: BlueXP backup and recovery
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Fornecedor de nuvem
    default: Todos os fornecedores de nuvem
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de backup e recuperação do BlueXP 
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Limitações conhecidas para cargas de trabalho do Microsoft SQL Server
      url: "/br-limitations.html"
    - title: Limitações conhecidas para cargas de trabalho de volumes ONTAP
      url: "/br-reference-limitations.html"
  - title: Comece agora
    entries:
    - title: Saiba mais sobre o backup e a recuperação do BlueXP 
      url: "/concept-backup-to-cloud.html"
    - title: Pré-requisitos para BlueXP backup and recovery
      url: "/concept-start-prereq.html"
    - title: Configure o licenciamento para backup e recuperação do BlueXP
      url: "/br-start-licensing.html"
    - title: Configure destinos de backup antes de usar o BlueXP backup and recovery
      url: "/br-start-setup.html"
    - title: Faça login no BlueXP backup and recovery
      url: "/br-start-login.html"
    - title: Descubra alvos de backup
      url: "/br-start-discover-backup-targets.html"
    - title: Mude para diferentes cargas de trabalho de BlueXP backup and recovery
      url: "/br-start-switch-ui.html"
    - title: Configurar as configurações gerais de BlueXP backup and recovery
      url: "/br-start-configure.html"
  - title: Use o BlueXP backup and recovery
    entries:
    - title: Visualizar a saúde da proteção no Painel
      url: "/br-use-dashboard.html"
    - title: Crie políticas para governar backups e restaurações
      url: "/br-use-policies-create.html"
    - title: Proteja cargas de trabalho de volume ONTAP
      entries:
      - title: Visão geral das cargas de trabalho de volume Protect ONTAP
        url: "/prev-ontap-protect-overview.html"
      - title: Planeje sua jornada de proteção para volumes ONTAP
        url: "/prev-ontap-protect-journey.html"
      - title: Gerenciar políticas para ONTAP volumes
        url: "/prev-ontap-policy-manage.html"
      - title: Opções de política de backup para objeto para volumes ONTAP
        url: "/prev-ontap-policy-object-options.html"
      - title: Gerenciar opções de configurações avançadas da política de backup para
          objeto
        url: "/prev-ontap-policy-object-advanced-settings.html"
      - title: Faça backup do Cloud Volumes ONTAP para o Amazon S3
        url: "/prev-ontap-backup-cvo-aws.html"
      - title: Faça backup do Cloud Volumes ONTAP para o Azure Blob
        url: "/prev-ontap-backup-cvo-azure.html"
      - title: Faça backup do Cloud Volumes ONTAP para o Google Cloud
        url: "/prev-ontap-backup-cvo-gcp.html"
      - title: Fazer backup do ONTAP no local para o Amazon S3
        url: "/prev-ontap-backup-onprem-aws.html"
      - title: Fazer backup do ONTAP no local para Azure Blob
        url: "/prev-ontap-backup-onprem-azure.html"
      - title: Fazer backup do ONTAP no local para o Google Cloud
        url: "/prev-ontap-backup-onprem-gcp.html"
      - title: Fazer backup do ONTAP no local para o ONTAP S3
        url: "/prev-ontap-backup-onprem-ontaps3.html"
      - title: Fazer backup do ONTAP no local para o StorageGRID
        url: "/prev-ontap-backup-onprem-storagegrid.html"
      - title: Migre volumes usando o SnapMirror para o Cloud Resync
        url: "/prev-ontap-migrate-resync.html"
      - title: Gerenciar backups do ONTAP
        url: "/prev-ontap-backup-manage.html"
      - title: Restauração a partir de backups do ONTAP
        url: "/prev-ontap-restore.html"
    - title: Proteja as cargas de trabalho do Microsoft SQL Server (visualização)
      entries:
      - title: Visão geral da proteção de cargas de trabalho do Microsoft SQL Server
        url: "/br-use-mssql-protect-overview.html"
      - title: Configurar itens adicionais se importar do SnapCenter
        url: "/concept-start-prereq-snapcenter-import.html"
      - title: Descubra as cargas de trabalho do Microsoft SQL Server
        url: "/br-start-discover.html"
      - title: Fazer backup de cargas de trabalho do Microsoft SQL Server
        url: "/br-use-mssql-backup.html"
      - title: Restaurar cargas de trabalho do Microsoft SQL Server
        url: "/br-use-mssql-restore.html"
      - title: Clonar cargas de trabalho do Microsoft SQL Server
        url: "/br-use-mssql-clone.html"
      - title: Gerenciar inventário do Microsoft SQL Server
        url: "/br-use-manage-inventory.html"
      - title: Gerenciar instantâneos do Microsoft SQL Server
        url: "/br-use-manage-snapshots.html"
      - title: Criar relatórios do Microsoft SQL Server
        url: "/br-use-reports.html"
    - title: Proteja cargas de trabalho de máquinas virtuais
      entries:
      - title: Visão geral da proteção de cargas de trabalho de máquinas virtuais
        url: "/prev-vmware-protect-overview.html"
      - title: Pré-requisitos para proteger cargas de trabalho de máquinas virtuais
        url: "/prev-vmware-prereqs.html"
      - title: Registre o plug-in do SnapCenter para o host VMware vSphere
        url: "/prev-vmware-register-snapcenter.html"
      - title: Crie uma política para fazer backup de dados da máquina virtual
        url: "/prev-vmware-policy-create.html"
      - title: Faça backup de armazenamentos de dados no Amazon Web Services
        url: "/prev-vmware-backup-aws.html"
      - title: Faça backup de armazenamentos de dados no Microsoft Azure
        url: "/prev-vmware-backup-azure.html"
      - title: Faça backup de armazenamentos de dados no Google Cloud Platform
        url: "/prev-vmware-backup-gcp.html"
      - title: Faça backup de armazenamentos de dados no StorageGRID
        url: "/prev-vmware-backup-storagegrid.html"
      - title: Gerenciar a proteção dos dados de datastores e máquinas virtuais
        url: "/prev-vmware-manage.html"
      - title: Restaurar dados e armazenamentos de dados de máquinas virtuais
        url: "/prev-vmware-restore.html"
    - title: Monitorizar trabalhos
      url: "/br-use-monitor-tasks.html"
    - title: Reinicie o backup e a recuperação do BlueXP 
      url: "/reference-restart-backup.html"
  - title: Automatize com a API REST
    url: "/br-api-backup-restore.html"
  - title: Referência
    entries:
    - title: Políticas no SnapCenter comparadas ao BlueXP backup and recovery
      url: "/reference-policy-differences-snapcenter.html"
    - title: Funções e privilégios de BlueXP backup and recovery
      url: "/reference-roles.html"
    - title: Camadas de storage de arquivamento AWS compatíveis
      url: "/prev-reference-aws-archive-storage-tiers.html"
    - title: Camadas de armazenamento de arquivo do Azure com suporte
      url: "/prev-reference-azure-archive-storage-tiers.html"
    - title: Níveis de armazenamento de arquivo do Google Cloud compatíveis
      url: "/prev-reference-gcp-archive-storage-tiers.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
