---
settings:
  name: BlueXP backup and recovery
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  filter:
    label: Fornecedor de nuvem
    default: Todos os fornecedores de nuvem
    options:
    - name: Amazon Web Services
      alias: AWS
      id: aws
    - name: Google Cloud
      alias: Google Cloud
      id: gcp
    - name: Microsoft Azure
      alias: Azure
      id: azure
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de backup e recuperação do BlueXP 
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Limitações conhecidas
      url: "/reference-limitations.html"
  - title: Comece agora
    entries:
    - title: Saiba mais sobre o backup e a recuperação do BlueXP 
      url: "/concept-backup-to-cloud.html"
    - title: Configure o licenciamento
      url: "/task-licensing-cloud-backup.html"
  - title: Monitorar a proteção de dados
    entries:
    - title: Relatório sobre a cobertura de proteção de dados
      url: "/task-report-inventory.html"
    - title: Monitore o status dos trabalhos de backup e restauração
      url: "/task-monitor-backup-jobs.html"
  - title: Faça backup e restaure dados do ONTAP
    entries:
    - title: Proteger os dados de volume do ONTAP
      url: "/concept-ontap-backup-to-cloud.html"
    - title: Planeje sua jornada de proteção
      url: "/concept-protection-journey.html"
    - title: Gerenciar políticas para ONTAP volumes
      url: "/task-create-policies-ontap.html"
    - title: Opções de política de backup para objeto
      url: "/concept-cloud-backup-policies.html"
    - title: Gerencie opções de backup para objeto em Configurações avançadas
      url: "/task-manage-backup-settings-ontap.html"
    - title: Faça backup do Cloud Volumes ONTAP para o Amazon S3
      flavor: aws
      url: "/task-backup-to-s3.html"
    - title: Faça backup do Cloud Volumes ONTAP para o Azure Blob
      flavor: azure
      url: "/task-backup-to-azure.html"
    - title: Faça backup do Cloud Volumes ONTAP para o Google Cloud
      flavor: gcp
      url: "/task-backup-to-gcp.html"
    - title: Fazer backup do ONTAP no local para o Amazon S3
      flavor: aws
      url: "/task-backup-onprem-to-aws.html"
    - title: Fazer backup do ONTAP no local para Azure Blob
      flavor: azure
      url: "/task-backup-onprem-to-azure.html"
    - title: Fazer backup do ONTAP no local para o Google Cloud
      flavor: gcp
      url: "/task-backup-onprem-to-gcp.html"
    - title: Fazer backup do ONTAP no local para o ONTAP S3
      url: "/task-backup-onprem-to-ontap-s3.html"
    - title: Fazer backup do ONTAP no local para o StorageGRID
      url: "/task-backup-onprem-private-cloud.html"
    - title: Gerenciar backups do ONTAP
      url: "/task-manage-backups-ontap.html"
    - title: Restauração a partir de backups do ONTAP
      url: "/task-restore-backups-ontap.html"
  - title: Fazer backup e restaurar dados de aplicações no local
    entries:
    - title: Proteja os dados das aplicações no local
      url: "/concept-protect-app-data-to-cloud.html"
    - title: Registre o servidor SnapCenter
      url: "/task-register-snapcenter-server.html"
    - title: Crie uma política para fazer backup de aplicativos
      url: "/task-create-policies-apps.html"
    - title: Faça backup dos dados de aplicativos locais para o Amazon Web Services
      flavor: aws
      url: "/task-backup-app-data-to-aws.html"
    - title: Faça backup dos dados das aplicações locais para o Microsoft Azure
      flavor: azure
      url: "/task-backup-app-data-to-azure.html"
    - title: Fazer backup dos dados das aplicações locais no Google Cloud
      flavor: gcp
      url: "/task-backup-app-data-to-gcp.html"
    - title: Fazer backup dos dados das aplicações locais no StorageGRID
      url: "/task-backup-app-data-to-storagegrid.html"
    - title: Gerenciar a proteção de aplicativos
      url: "/task-manage-app-backups.html"
    - title: Restaure os dados das aplicações no local
      entries:
      - title: Restaure o banco de dados Oracle
        url: "/task-restore-oracle-data.html"
      - title: Restaure o banco de dados do SQL Server
        url: "/task-restore-sql-data.html"
      - title: Restaure o banco de dados SAP HANA
        url: "/task-restore-hana-backup.html"
      - title: Restaure bancos de dados MongoDB, MySQL e PostgreSQL
        url: "/task-restore-customplugin-backup.html"
  - title: Faça backup e restaure os dados das máquinas virtuais
    entries:
    - title: Proteja seus dados de máquinas virtuais
      url: "/concept-protect-vm-data.html"
    - title: Registre o plug-in do SnapCenter para o host VMware vSphere
      url: "/task-register-snapCenter-plug-in-for-vmware-vsphere.html"
    - title: Crie uma política para fazer backup de armazenamentos de dados
      url: "/task-create-policies-vms.html"
    - title: Faça backup de armazenamentos de dados no Amazon Web Services
      flavor: aws
      url: "/task-backup-vm-data-to-aws.html"
    - title: Faça backup de armazenamentos de dados no Microsoft Azure
      flavor: azure
      url: "/task-backup-vm-data-to-azure.html"
    - title: Faça backup de armazenamentos de dados no Google Cloud Platform
      flavor: gcp
      url: "/task-backup-vm-data-to-gcp.html"
    - title: Faça backup de armazenamentos de dados no StorageGRID
      url: "/task-backup-vm-data-to-storagegrid.html"
    - title: Gerenciar a proteção dos dados de datastores e máquinas virtuais
      url: "/task-manage-vm-data-in-cloud.html"
    - title: Restaure os dados das máquinas virtuais
      url: "/task-restore-vm-data.html"
  - title: Automatize com a API REST
    url: "/api-backup-restore.html"
  - title: Referência
    entries:
    - title: Camadas de storage de arquivamento AWS compatíveis
      url: "/reference-aws-backup-tiers.html"
    - title: Camadas de acesso de arquivamento do Azure compatíveis
      url: "/reference-azure-backup-tiers.html"
    - title: Categorias de storage de arquivamento do Google compatíveis
      url: "/reference-google-backup-tiers.html"
    - title: Configure o backup para acesso a várias contas no Azure
      flavor: azure
      url: "/reference-backup-multi-account-azure.html"
    - title: Restaure o banco de dados de backup e recuperação do BlueXP  em um local
        escuro
      url: "/reference-backup-cbs-db-in-dark-site.html"
    - title: Reinicie o backup e a recuperação do BlueXP 
      url: "/reference-restart-backup.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/task-support-registration.html"
    - title: Obtenha ajuda
      url: "/task-get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
