---
sidebar: sidebar 
permalink: reference-google-backup-tiers.html 
keywords: google, storage classes, archive 
summary: Backup e recuperação do BlueXP  são compatíveis com uma classe de storage de arquivamento do Google e a maioria das regiões. 
---
= Classes de armazenamento de arquivamento do Google e restaurar tempos de recuperação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Backup e recuperação do BlueXP  são compatíveis com uma classe de storage de arquivamento do Google e a maioria das regiões.



== Classes de armazenamento de arquivamento do Google compatíveis para backup e recuperação do BlueXP 

Quando os arquivos de backup são criados inicialmente, eles são armazenados no armazenamento _Standard_. Esse nível é otimizado para armazenar dados que são acessados com pouca frequência, mas que também permite acessá-los imediatamente.

Se o cluster no local estiver usando o ONTAP 9.12,1 ou superior, você poderá optar por categorizar backups mais antigos para o storage _Archive_ na IU de backup e recuperação do BlueXP  após um determinado número de dias (geralmente mais de 30 dias) para otimização adicional de custos. Os dados nesse nível exigirão um custo de recuperação mais alto, então você precisa considerar com que frequência você pode precisar restaurar dados desses arquivos de backup arquivados. Consulte a seção nesta página sobre como restaurar dados do armazenamento de arquivos.

Observe que ao configurar o backup e a recuperação do BlueXP  com esse tipo de regra de ciclo de vida, você não deve configurar nenhuma regra de ciclo de vida ao configurar o bucket em sua conta do Google.

https://cloud.google.com/storage/docs/storage-classes["Saiba mais sobre as classes de armazenamento do Google"^].



== Restaurar dados do armazenamento de arquivamento

Embora armazenar arquivos de backup mais antigos no armazenamento de arquivos seja muito mais barato do que o armazenamento padrão, acessar dados de um arquivo de backup no armazenamento de arquivos para operações de restauração levará um pouco mais de tempo e custará mais dinheiro.

Quanto custa restaurar dados do Google Archive?:: Para obter preços detalhados do Google Cloud Storage por região, visite o https://cloud.google.com/storage/pricing["Página de preços do Google Cloud Storage"^].
Quanto tempo levará para restaurar meus objetos arquivados no Google Archive?:: Existem 2 partes que compõem o tempo total de restauração:
+
--
* *Tempo de recuperação*: O tempo para recuperar o arquivo de backup do Archive e colocá-lo em armazenamento padrão. Isso às vezes é chamado de tempo de "reidratação". Ao contrário das soluções de storage "mais frias" fornecidas por outros fornecedores de nuvem, seus dados ficam acessíveis em milissegundos.
* *Tempo de restauração*: O tempo para restaurar os dados do arquivo de backup no armazenamento padrão. Esse tempo não é diferente da operação de restauração típica diretamente do armazenamento padrão, quando não está usando uma camada de arquivamento.


--

