---
sidebar: sidebar 
permalink: task-report-inventory.html 
keywords: cloud backup, backup and recovery service, backup and recovery, backup, restore, report, inventory, bluexp 
summary: Com os relatórios de backup e recuperação do BlueXP , você garante a proteção dos dados essenciais de acordo com as políticas definidas pela sua organização e oferece suporte eficiente à auditoria de processos de conformidade. Com o relatório de inventário de backup, você pode ver todos os backups de uma conta específica, ambiente de trabalho ou inventário de SVM. 
---
= Relatório sobre a cobertura de proteção de dados com backup e recuperação BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Com os relatórios de backup e recuperação do BlueXP, garanta que dados críticos estejam protegidos de acordo com as políticas definidas pela sua organização e forneça auditorias para necessidades de conformidade.

Os relatórios de backup e recuperação do BlueXP  ajudam você a realizar o seguinte:

* *Visibilidade das operações*: Monitore seus contratos de nível de serviço com relação à proteção de dados, taxa de sucesso de backup e alinhamento de janelas de backup às necessidades de negócios.
* * Conformidade e auditoria*: Use relatórios operacionais e de inventário em seus processos de auditoria interna e externa para monitoramento contínuo da conformidade.



NOTE: As atividades de relatório são monitorizadas no registo de monitorização de trabalhos para que possa auditar todas as atividades. link:task-monitor-backup-jobs.html["Saiba mais sobre Monitoramento de trabalhos"].



== Escopo dos relatórios

Os relatórios de backup e recuperação do BlueXP  fornecem informações sobre os seguintes aspetos:

* *Localização do conetor*: No local ou na nuvem
* *Origem*: Volumes Cloud Volumes ONTAP, volumes ONTAP locais ou aplicações
* *Destino*: Qualquer um dos provedores de nuvem, NetApp StorageGRID ou ONTAP S3
* *Versões ONTAP*: 9.13.0




== Criar um relatório de inventário de backup

Na guia relatórios de backup e recuperação do BlueXP , você pode criar o relatório de inventário de backup e filtrar seu conteúdo. Com o relatório Backup Inventory, você pode ver todos os backups de uma conta específica, ambiente de trabalho ou inventário de SVM.

O relatório Backup Inventory mostra as seguintes informações e muito mais:

* Conta, ambiente de trabalho e SVM
* Volumes protegidos e não protegidos
* Destino de backup
* Política de backup aplicada
* Estilo de criptografia (chave gerenciada pelo provedor ou chave gerenciada pelo usuário)
* Status de proteção DataLock e ransomware (governança, conformidade ou nenhuma)
* Estado de arquivamento ativado
* Contagem de cópias de backup
* Tipo de cópia de segurança (cópia de segurança ad-hoc agendada ou iniciada pelo utilizador)
* Classe de armazenamento
* Etiqueta do instantâneo



NOTE: O relatório Backup Inventory não inclui informações de backup expiradas ou com falha.

A parte superior do relatório inclui um gráfico que mostra as seguintes informações:

* Contagem de volumes no escopo com pelo menos um backup
* Total de volumes inativos mais volumes ativos


O relatório Backup Inventory mostra os seguintes gráficos:

* *Status do backup de volume*: Mostra protegido em comparação com volumes não protegidos para o escopo selecionado.
* *Volumes por contagem de backup*: Agrupa volumes pelo número de cópias de backup disponíveis para esse volume.


.Passos
. No menu superior, selecione *relatórios*.
. Selecione *Backup de inventário*.
. Selecione *criar relatório*.
. Selecione a conta, o ambiente de trabalho e o SVM.
+

TIP: Você pode selecionar vários ambientes de trabalho e SVMs.

. Selecione o período de tempo: Últimas 24 horas, semana ou mês.
. Revise as seções do relatório (políticas Snapshot, políticas de replicação ou políticas de backup), dependendo das seleções de relatório.
. (Opcional) Filtrar os resultados por status do trabalho.
. (Opcional) Exporte o conteúdo do relatório no formato .CSV selecionando *Download CSV*.




== Criar um relatório de atividade de trabalho de proteção de dados

O monitoramento proativo pode reduzir o esforço necessário para monitorar todos os recursos em seu ecossistema. A partir do ONTAP 9.13,0, o relatório atividade de trabalho de proteção de dados fornece informações sobre operações de snapshot, backup, clone e restauração que você pode usar com o monitoramento de SLA e rastrear taxas de backup e recuperação.

O relatório se aplica às operações de backup e recuperação do BlueXP  para dados de Cloud Volumes ONTAP, on-premises e aplicações.

O relatório atividade trabalho proteção de dados mostra as seguintes informações e muito mais:

* Conta, ambiente de trabalho e SVM
* Tipo de tarefa (backup ou restauração)
* Nome do recurso (volume ou aplicativo)
* Estado do trabalho
* Horários de início e fim e duração
* Nome da política para trabalhos de cópia de segurança
* Etiqueta Snapshot para trabalhos de cópia de segurança


Os gráficos na parte superior da página mostram as seguintes informações:

* Trabalhos por tipo
+
** Contagem de tarefas de backup e restauração do ONTAP volumes
** Contagem dos trabalhos de cópia de segurança e restauro de aplicações
** Contagem de tarefas de backup e restauração de máquinas virtuais


* Atividade de trabalho diária


.Passos
. No menu superior, selecione *relatórios*.
. Selecione *atividade do trabalho de proteção de dados*.
. Selecione *criar relatório*.
. Selecione a conta, o ambiente de trabalho e o SVM.
. Selecione o período de tempo: Últimas 24 horas, semana ou mês.
. (Opcional) Filtrar os resultados por status da tarefa, tipos de tarefa (backup ou restauração) e recurso.
. (Opcional) Exporte o conteúdo do relatório no formato .CSV selecionando *Download CSV*.

