---
sidebar: sidebar 
permalink: task-register-snapCenter-plug-in-for-vmware-vsphere.html 
keywords: register, registration, SnapCenter Plug-in for VMware vSphere 
summary: Registre o plug-in do SnapCenter para o host VMware vSphere no BlueXP . 
---
= Registre o plug-in do SnapCenter para o host VMware vSphere
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você deve Registrar o plug-in do SnapCenter para o host VMware vSphere no BlueXP  para que os datastores e as máquinas virtuais sejam exibidos. Somente um usuário com acesso administrativo pode Registrar o plug-in do SnapCenter para o host VMware vSphere.

.Passos
. Na IU do BlueXP , clique em *proteção* > *Backup e recuperação* > *máquinas virtuais*.
. Na lista suspensa *Configurações*, clique em *Plug-in SnapCenter para VMware vSphere*.
. Clique em *Register SnapCenter Plug-in para VMware vSphere*.
. Especifique os seguintes detalhes:
+
.. No campo Plug-in do SnapCenter para VMware vSphere, especifique o FQDN ou o endereço IP do plug-in do SnapCenter para o host VMware vSphere.
.. No campo porta , especifique o número da porta na qual o plug-in do SnapCenter para o host VMware vSphere está sendo executado.
+
Você deve garantir que a comunicação esteja aberta entre o plug-in do SnapCenter no local para o host VMware vSphere que está sendo executado na porta 8144 padrão e na instância do BlueXP  Connector que pode ser executado em qualquer provedor de nuvem (Amazon Web Services, Microsoft Azure, Google Cloud Platform) ou no local.

.. No campo Nome de usuário e senha , especifique as credenciais do usuário do vCenter com a função de administrador.


. Clique em *Register*.


*Depois de terminar*

Clique em *Backup e recuperação* > *máquinas virtuais* para visualizar todos os datastores e máquinas virtuais protegidos usando o plug-in SnapCenter registrado para o host VMware vSphere.
