= Restaure volumes com menos de 1 GB
:allow-uri-read: 




=== Restaure volumes com menos de 1 GB

Com esta versão, agora você pode restaurar volumes criados no ONTAP com menos de 1 GB. O tamanho mínimo de volume que você pode criar usando o ONTAP é de 20 MB.



=== Dicas sobre como mitigar os custos do DataLock

O recurso DataLock protege seus arquivos de backup de serem modificados ou excluídos por um período de tempo especificado. Isso é útil para proteger seus arquivos contra ataques de ransomware.

Para obter detalhes sobre o DataLock e dicas sobre como mitigar os custos associados, https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-cloud-backup-policies.html["Configurações de política de backup para objeto"] consulte .



=== Integração com o AWS IAM em qualquer lugar

O serviço Amazon Web Services (AWS) Identity and Access Management (IAM) Role Anywhere permite que você use funções do IAM e credenciais de curto prazo para suas cargas de trabalho _fora_ da AWS para acessar APIs da AWS com segurança, da mesma forma que você usa funções do IAM para cargas de trabalho _on_ AWS. Quando você usa funções do IAM em qualquer infraestrutura de chave privada e tokens da AWS, não precisa de chaves de acesso e chaves secretas de longo prazo da AWS. Isso permite que você gire as credenciais com mais frequência, melhorando a segurança.

Com esta versão, o suporte para o serviço AWS IAM Roles Anywhere é uma prévia da tecnologia.

ifdef::aws[]

Isto aplica-se ao link:task-backup-to-s3.html["Fazer backup do Cloud Volumes ONTAP para a AWS"]. Isto aplica-se ao link:task-backup-onprem-to-aws.html["Fazer backup de dados ONTAP on-premises para a AWS"].

endif::aws[]

Consulte a https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Blog de lançamento de backup e recuperação do BlueXP  em julho de 2024"].



=== Pasta FlexGroup ou restauração de diretório agora disponível

Anteriormente, os volumes do FlexVol podiam ser restaurados, mas não era possível restaurar pastas ou diretórios do FlexGroup. Com o ONTAP 9.15,1 P2, você pode restaurar pastas do FlexGroup usando a opção Procurar e restaurar.

Com esta versão, o suporte para a restauração de pastas FlexGroup é uma prévia da tecnologia.

Para obter detalhes, https://docs.netapp.com/us-en/bluexp-backup-recovery/task-restore-backups-ontap.html#restore-ontap-data-using-browse-restore["Restaure pastas e ficheiros utilizando Procurar  Restaurar"] consulte .

Para obter detalhes para ativá-lo manualmente, https://community.netapp.com/t5/Tech-ONTAP-Blogs/BlueXP-Backup-and-Recovery-July-2024-Release/ba-p/453993["Blog de lançamento de backup e recuperação do BlueXP  em julho de 2024"] consulte .
