= Suporte a Podman no RHEL 8 ou 9 com Browse and Restore
:allow-uri-read: 




=== Suporte a Podman no RHEL 8 ou 9 com Browse and Restore

O backup e a recuperação do BlueXP  agora suportam restaurações de arquivos e pastas no Red Hat Enterprise Linux (RHEL) versões 8 e 9 usando o mecanismo Podman. Isso se aplica ao método de pesquisa e restauração de backup e recuperação do BlueXP .

O BlueXP  Connector versão 3.9.40 suporta determinadas versões do Red Hat Enterprise Linux versões 8 e 9 para qualquer instalação manual do software Connector em um host RHEL 8 ou 9, independentemente do local, além dos sistemas operacionais mencionados no https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html#step-3-review-host-requirements["requisitos de host"^] . Essas novas versões RHEL requerem o mecanismo Podman em vez do mecanismo Docker. Anteriormente, o backup e a recuperação do BlueXP  tinham duas limitações ao usar o motor Podman. Estas limitações foram removidas.

https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["Saiba mais sobre como restaurar dados do ONTAP a partir de arquivos de backup"].



=== A indexação mais rápida do catálogo melhora a Pesquisa e a Restauração

Esta versão inclui um índice de catálogo melhorado que completa a indexação da linha de base muito mais rápido. A indexação mais rápida permite que você use o recurso Pesquisa e Restauração mais rapidamente.

https://docs.netapp.com/us-en/bluexp-backup-recovery/prev-ontap-restore.html["Saiba mais sobre como restaurar dados do ONTAP a partir de arquivos de backup"].
