= Painel de controlo de volume melhorado (pré-visualização)
:allow-uri-read: 




=== Painel de controlo de volume melhorado (pré-visualização)

O Painel de volume agora é carregado em menos de 10 segundos, fornecendo uma interface muito mais rápida e eficiente. Esta versão de pré-visualização está disponível para clientes selecionados, oferecendo-lhes uma visão antecipada dessas melhorias.



=== Melhorias na IU

Esta versão melhora sua experiência simplificando a interface:

* A remoção da coluna agregada das tabelas volumes, juntamente com as colunas Política de snapshot, Política de backup e Política de replicação da tabela volume no Painel V2, resulta em um layout mais simplificado.
* A exclusão de ambientes de trabalho não ativados da lista suspensa torna a interface menos organizada, a navegação mais eficiente e o carregamento mais rápido.
* Enquanto a classificação na coluna Tags está desativada, você ainda pode visualizar as tags, garantindo que informações importantes permaneçam facilmente acessíveis.
* A remoção de etiquetas nos ícones de proteção contribui para uma aparência mais limpa e diminui o tempo de carregamento.
* Durante o processo de ativação do ambiente de trabalho, uma caixa de diálogo exibe um ícone de carregamento para fornecer feedback até que o processo de descoberta esteja concluído, aumentando a transparência e a confiança nas operações do sistema.




=== Suporte para armazenamento de objetos Wasabi de terceiros (Preview)

O backup e a recuperação do BlueXP  agora estendem seu suporte a armazenamentos de objetos de terceiros com foco principal no Wasabi. Este novo recurso de visualização permite que você aproveite qualquer armazenamento de objetos compatível com S3 para suas necessidades de backup e recuperação.



==== Introdução ao Wasabi

Para começar a usar esse recurso, você deve habilitar um sinalizador na IU do BlueXP . Em seguida, você pode inserir os detalhes de conexão do seu armazenamento de objetos de terceiros e integrá-los aos fluxos de trabalho de backup e recuperação.



==== Limitações do modo de visualização

Embora esse recurso esteja na visualização, considere as seguintes limitações:

* Bring Your own Bucket (BYOB) não é suportado.
* A ativação do DataLock em uma política não é suportada.
* A ativação do modo de arquivamento em uma política não é suportada.
* Somente ambientes ONTAP locais são compatíveis.
* O MetroCluster não é suportado.
* As opções para habilitar a criptografia no nível do bucket não são suportadas.


Durante essa visualização, recomendamos que você explore esse novo recurso e forneça feedback sobre a integração com armazenamentos de objetos de terceiros antes que a funcionalidade completa seja implementada.
