= Requisitos de rede da ONTAP no local
:allow-uri-read: 


Se você planeja criar volumes replicados em um sistema ONTAP secundário usando o backup e a recuperação do BlueXP , certifique-se de que os sistemas de origem e destino atendam aos seguintes requisitos de rede.



==== Requisitos de rede da ONTAP no local

* Se o cluster estiver em suas instalações, você deverá ter uma conexão da rede corporativa à rede virtual no provedor de nuvem. Normalmente, esta é uma conexão VPN.
* Os clusters do ONTAP devem atender a requisitos adicionais de sub-rede, porta, firewall e cluster.
+
Como você pode replicar para o Cloud Volumes ONTAP ou sistemas locais, revise os requisitos de peering para sistemas ONTAP locais. https://docs.netapp.com/us-en/ontap-sm-classic/peering/reference_prerequisites_for_cluster_peering.html["Veja os pré-requisitos para peering de cluster na documentação do ONTAP"^].





==== Requisitos de rede da Cloud Volumes ONTAP

* O grupo de segurança da instância deve incluir as regras de entrada e saída necessárias: Especificamente, regras para ICMP e portas 11104 e 11105. Essas regras estão incluídas no grupo de segurança predefinido.

